# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/FPGA/school_code/test_6dig/test_6dig.srcs/sources_1/ip/dynamic_led3_0/dynamic_led3_0.xci
# IP: The module: 'dynamic_led3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/school_code/test_6dig/test_6dig.srcs/sources_1/ip/dynamic_led3_0/constrs_1/new/con1.xdc
# XDC: The top module name and the constraint reference have the same name: 'dynamic_led3_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/FPGA/school_code/test_6dig/test_6dig.srcs/sources_1/ip/dynamic_led3_0/dynamic_led3_0.xci
# IP: The module: 'dynamic_led3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/school_code/test_6dig/test_6dig.srcs/sources_1/ip/dynamic_led3_0/constrs_1/new/con1.xdc
# XDC: The top module name and the constraint reference have the same name: 'dynamic_led3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
